version: '3'

services:

  workspace:
    build: ./Dockerfiles/workspace
    container_name: ploom_workspace
    volumes:
      - ../:/var/www/html
    command: bash
    environment:
      - STAGE=docker
    depends_on:
      - mysql
      - cache

  web:
    container_name: apache-php56
    build: ./Dockerfiles/web/php56
    ports:
      - '8001:80'
    environment:
      - STAGE=docker
    volumes:
      - ../:/var/www/html
    links:
      - mysql
      - cache

  mysql:
    image: mysql:5.6
    container_name: ploom201812_mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES utf8' --innodb_file_per_table=1 --innodb_file_format=BARRACUDA
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ploom_201812_mysql:/var/lib/mysql

  cache:
    container_name: memcached
    image: memcached

volumes:
    ploom_201812_mysql:
        driver: "local"

